name: "Check Build Changes"
description: "Check if build-relevant files have changed"

inputs:
  patterns-file:
    description: "Path to the patterns file"
    required: false
    default: ".make-build-patterns"
  before-ref:
    description: "The before commit reference"
    required: true
  current-sha:
    description: "The current commit SHA"
    required: true

outputs:
  build_required:
    description: "Whether a build is required"
    value: ${{ steps.check.outputs.build_required }}

runs:
  using: "composite"
  steps:
    - name: Check for build relevant file changes
      id: check
      shell: bash
      run: |
        set -e

        BEFORE_REF="${{ inputs.before-ref }}"
        PATTERNS_FILE="${{ inputs.patterns-file }}"

        # Handle case where there's no valid before reference (first commit, new branch, etc.)
        if [[ "$BEFORE_REF" == "0000000000000000000000000000000000000000" ]] || [[ -z "$BEFORE_REF" ]]; then
          echo "No valid previous commit found. Triggering full build."
          echo "build_required=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get list of changed files
        git fetch origin $BEFORE_REF --depth=1 2>/dev/null || true
        CHANGED_FILES=$(git diff --name-only $BEFORE_REF ${{ inputs.current-sha }} 2>/dev/null || echo "")

        # Special case: empty commit or diff failure triggers full build
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "Empty commit or unable to diff. Triggering full build."
          echo "build_required=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Load patterns from the specified file
        if [[ ! -f "$PATTERNS_FILE" ]]; then
          echo "Patterns file '$PATTERNS_FILE' not found. Triggering full build."
          echo "build_required=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        WATCHED_PATTERNS=$(cat "$PATTERNS_FILE")

        MATCHED_FILES=""
        for pattern in $WATCHED_PATTERNS; do
          for file in $CHANGED_FILES; do
            # Simple prefix/exact matching:
            # - "src/" matches any file starting with src/
            # - "Dockerfile" matches Dockerfile, Dockerfile.foo, etc.
            if [[ "$file" == "$pattern"* ]]; then
              MATCHED_FILES+=" $file"
            fi
          done
        done

        if [[ -n "$MATCHED_FILES" ]]; then
          echo "Found watched changes:$MATCHED_FILES"
          echo "build_required=true" >> $GITHUB_OUTPUT
        else
          echo "No watched file changes. Skipping build."
          echo "build_required=false" >> $GITHUB_OUTPUT
        fi
